/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup GCSReceiver GCSReceiver
 * @brief A receiver channel group carried over the telemetry link.
 *
 * Autogenerated files and functions for GCSReceiver Object
 *
 * @{
 *
 * @file       gcsreceiver.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the GCSReceiver object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: gcsreceiver.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef GCSRECEIVER_H
#define GCSRECEIVER_H
#include <stdbool.h>
/* Object constants */
#define GCSRECEIVER_OBJID 0xCC7E1470
#define GCSRECEIVER_ISSINGLEINST 1
#define GCSRECEIVER_ISSETTINGS 0
#define GCSRECEIVER_ISPRIORITY 0
#define GCSRECEIVER_NUMBYTES sizeof(GCSReceiverData)

/* Field Channel information */

// Number of elements for field Channel
#define GCSRECEIVER_CHANNEL_NUMELEM 8




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    uint16_t Channel[8];

} __attribute__((packed)) GCSReceiverDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef GCSReceiverDataPacked __attribute__((aligned(4))) GCSReceiverData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    GCSReceiverDataPacked data;
    byte arr[GCSRECEIVER_NUMBYTES];
 } GCSReceiverDataUnion;

#endif // GCSRECEIVER_H

/**
 * @}
 * @}
 */

