/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup ManualControlCommand ManualControlCommand
 * @brief The output from the @ref ManualControlModule which decodes the receiver inputs. Overriden by GCS for fly-by-wire control.
 *
 * Autogenerated files and functions for ManualControlCommand Object
 *
 * @{
 *
 * @file       manualcontrolcommand.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the ManualControlCommand object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: manualcontrolcommand.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef MANUALCONTROLCOMMAND_H
#define MANUALCONTROLCOMMAND_H
#include <stdbool.h>
/* Object constants */
#define MANUALCONTROLCOMMAND_OBJID 0x265BA97E
#define MANUALCONTROLCOMMAND_ISSINGLEINST 1
#define MANUALCONTROLCOMMAND_ISSETTINGS 0
#define MANUALCONTROLCOMMAND_ISPRIORITY 0
#define MANUALCONTROLCOMMAND_NUMBYTES sizeof(ManualControlCommandData)

/* Field Throttle information */

/* Field Roll information */

/* Field Pitch information */

/* Field Yaw information */

/* Field Collective information */

/* Field Thrust information */

/* Field Channel information */

// Number of elements for field Channel
#define MANUALCONTROLCOMMAND_CHANNEL_NUMELEM 11

/* Field Connected information */

// Enumeration options for field Connected
typedef enum __attribute__ ((__packed__)) {
    MANUALCONTROLCOMMAND_CONNECTED_FALSE=0,
    MANUALCONTROLCOMMAND_CONNECTED_TRUE=1
} ManualControlCommandConnectedOptions;

/* Field FlightModeSwitchPosition information */




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float Throttle;
    float Roll;
    float Pitch;
    float Yaw;
    float Collective;
    float Thrust;
    uint16_t Channel[11];
    ManualControlCommandConnectedOptions Connected;
    uint8_t FlightModeSwitchPosition;

} __attribute__((packed)) ManualControlCommandDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef ManualControlCommandDataPacked __attribute__((aligned(4))) ManualControlCommandData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    ManualControlCommandDataPacked data;
    byte arr[MANUALCONTROLCOMMAND_NUMBYTES];
 } ManualControlCommandDataUnion;

#endif // MANUALCONTROLCOMMAND_H

/**
 * @}
 * @}
 */

