/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup ManualControlSettings ManualControlSettings
 * @brief Settings to indicate how to decode receiver input by @ref ManualControlModule.
 *
 * Autogenerated files and functions for ManualControlSettings Object
 *
 * @{
 *
 * @file       manualcontrolsettings.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the ManualControlSettings object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: manualcontrolsettings.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef MANUALCONTROLSETTINGS_H
#define MANUALCONTROLSETTINGS_H
#include <stdbool.h>
/* Object constants */
#define MANUALCONTROLSETTINGS_OBJID 0xC2C59876
#define MANUALCONTROLSETTINGS_ISSINGLEINST 1
#define MANUALCONTROLSETTINGS_ISSETTINGS 1
#define MANUALCONTROLSETTINGS_ISPRIORITY 0
#define MANUALCONTROLSETTINGS_NUMBYTES sizeof(ManualControlSettingsData)

/* Field FailsafeChannel information */

// Array element names for field FailsafeChannel
typedef enum {
    MANUALCONTROLSETTINGS_FAILSAFECHANNEL_THROTTLE=0,
    MANUALCONTROLSETTINGS_FAILSAFECHANNEL_ROLL=1,
    MANUALCONTROLSETTINGS_FAILSAFECHANNEL_PITCH=2,
    MANUALCONTROLSETTINGS_FAILSAFECHANNEL_YAW=3,
    MANUALCONTROLSETTINGS_FAILSAFECHANNEL_COLLECTIVE=4,
    MANUALCONTROLSETTINGS_FAILSAFECHANNEL_ACCESSORY0=5,
    MANUALCONTROLSETTINGS_FAILSAFECHANNEL_ACCESSORY1=6,
    MANUALCONTROLSETTINGS_FAILSAFECHANNEL_ACCESSORY2=7,
    MANUALCONTROLSETTINGS_FAILSAFECHANNEL_ACCESSORY3=8
} ManualControlSettingsFailsafeChannelElem;

// Number of elements for field FailsafeChannel
#define MANUALCONTROLSETTINGS_FAILSAFECHANNEL_NUMELEM 9

/* Field ChannelMin information */

// Array element names for field ChannelMin
typedef enum {
    MANUALCONTROLSETTINGS_CHANNELMIN_THROTTLE=0,
    MANUALCONTROLSETTINGS_CHANNELMIN_ROLL=1,
    MANUALCONTROLSETTINGS_CHANNELMIN_PITCH=2,
    MANUALCONTROLSETTINGS_CHANNELMIN_YAW=3,
    MANUALCONTROLSETTINGS_CHANNELMIN_FLIGHTMODE=4,
    MANUALCONTROLSETTINGS_CHANNELMIN_COLLECTIVE=5,
    MANUALCONTROLSETTINGS_CHANNELMIN_ACCESSORY0=6,
    MANUALCONTROLSETTINGS_CHANNELMIN_ACCESSORY1=7,
    MANUALCONTROLSETTINGS_CHANNELMIN_ACCESSORY2=8,
    MANUALCONTROLSETTINGS_CHANNELMIN_ACCESSORY3=9,
    MANUALCONTROLSETTINGS_CHANNELMIN_RSSI=10
} ManualControlSettingsChannelMinElem;

// Number of elements for field ChannelMin
#define MANUALCONTROLSETTINGS_CHANNELMIN_NUMELEM 11

/* Field ChannelNeutral information */

// Array element names for field ChannelNeutral
typedef enum {
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_THROTTLE=0,
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_ROLL=1,
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_PITCH=2,
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_YAW=3,
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_FLIGHTMODE=4,
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_COLLECTIVE=5,
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_ACCESSORY0=6,
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_ACCESSORY1=7,
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_ACCESSORY2=8,
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_ACCESSORY3=9,
    MANUALCONTROLSETTINGS_CHANNELNEUTRAL_RSSI=10
} ManualControlSettingsChannelNeutralElem;

// Number of elements for field ChannelNeutral
#define MANUALCONTROLSETTINGS_CHANNELNEUTRAL_NUMELEM 11

/* Field ChannelMax information */

// Array element names for field ChannelMax
typedef enum {
    MANUALCONTROLSETTINGS_CHANNELMAX_THROTTLE=0,
    MANUALCONTROLSETTINGS_CHANNELMAX_ROLL=1,
    MANUALCONTROLSETTINGS_CHANNELMAX_PITCH=2,
    MANUALCONTROLSETTINGS_CHANNELMAX_YAW=3,
    MANUALCONTROLSETTINGS_CHANNELMAX_FLIGHTMODE=4,
    MANUALCONTROLSETTINGS_CHANNELMAX_COLLECTIVE=5,
    MANUALCONTROLSETTINGS_CHANNELMAX_ACCESSORY0=6,
    MANUALCONTROLSETTINGS_CHANNELMAX_ACCESSORY1=7,
    MANUALCONTROLSETTINGS_CHANNELMAX_ACCESSORY2=8,
    MANUALCONTROLSETTINGS_CHANNELMAX_ACCESSORY3=9,
    MANUALCONTROLSETTINGS_CHANNELMAX_RSSI=10
} ManualControlSettingsChannelMaxElem;

// Number of elements for field ChannelMax
#define MANUALCONTROLSETTINGS_CHANNELMAX_NUMELEM 11

/* Field ResponseTime information */

// Array element names for field ResponseTime
typedef enum {
    MANUALCONTROLSETTINGS_RESPONSETIME_ROLL=0,
    MANUALCONTROLSETTINGS_RESPONSETIME_PITCH=1,
    MANUALCONTROLSETTINGS_RESPONSETIME_YAW=2,
    MANUALCONTROLSETTINGS_RESPONSETIME_COLLECTIVE=3,
    MANUALCONTROLSETTINGS_RESPONSETIME_ACCESSORY0=4,
    MANUALCONTROLSETTINGS_RESPONSETIME_ACCESSORY1=5,
    MANUALCONTROLSETTINGS_RESPONSETIME_ACCESSORY2=6,
    MANUALCONTROLSETTINGS_RESPONSETIME_ACCESSORY3=7,
    MANUALCONTROLSETTINGS_RESPONSETIME_RSSI=8
} ManualControlSettingsResponseTimeElem;

// Number of elements for field ResponseTime
#define MANUALCONTROLSETTINGS_RESPONSETIME_NUMELEM 9

/* Field ChannelGroups information */

// Enumeration options for field ChannelGroups
typedef enum __attribute__ ((__packed__)) {
    MANUALCONTROLSETTINGS_CHANNELGROUPS_PWM=0,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_PPM=1,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_DSMMAINPORT=2,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_DSMFLEXIPORT=3,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_DSMRCVRPORT=4,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_SBUS=5,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_EXBUS=6,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_HOTT=7,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_SRXL=8,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_IBUS=9,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_GCS=10,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_OPLINK=11,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_OPENLRS=12,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_NONE=13
} ManualControlSettingsChannelGroupsOptions;

// Array element names for field ChannelGroups
typedef enum {
    MANUALCONTROLSETTINGS_CHANNELGROUPS_THROTTLE=0,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_ROLL=1,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_PITCH=2,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_YAW=3,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_FLIGHTMODE=4,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_COLLECTIVE=5,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_ACCESSORY0=6,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_ACCESSORY1=7,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_ACCESSORY2=8,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_ACCESSORY3=9,
    MANUALCONTROLSETTINGS_CHANNELGROUPS_RSSI=10
} ManualControlSettingsChannelGroupsElem;

// Number of elements for field ChannelGroups
#define MANUALCONTROLSETTINGS_CHANNELGROUPS_NUMELEM 11

/* Field ChannelNumber information */

// Array element names for field ChannelNumber
typedef enum {
    MANUALCONTROLSETTINGS_CHANNELNUMBER_THROTTLE=0,
    MANUALCONTROLSETTINGS_CHANNELNUMBER_ROLL=1,
    MANUALCONTROLSETTINGS_CHANNELNUMBER_PITCH=2,
    MANUALCONTROLSETTINGS_CHANNELNUMBER_YAW=3,
    MANUALCONTROLSETTINGS_CHANNELNUMBER_FLIGHTMODE=4,
    MANUALCONTROLSETTINGS_CHANNELNUMBER_COLLECTIVE=5,
    MANUALCONTROLSETTINGS_CHANNELNUMBER_ACCESSORY0=6,
    MANUALCONTROLSETTINGS_CHANNELNUMBER_ACCESSORY1=7,
    MANUALCONTROLSETTINGS_CHANNELNUMBER_ACCESSORY2=8,
    MANUALCONTROLSETTINGS_CHANNELNUMBER_ACCESSORY3=9,
    MANUALCONTROLSETTINGS_CHANNELNUMBER_RSSI=10
} ManualControlSettingsChannelNumberElem;

// Number of elements for field ChannelNumber
#define MANUALCONTROLSETTINGS_CHANNELNUMBER_NUMELEM 11

/* Field Deadband information */

/* Field DeadbandAssistedControl information */

/* Field FlightModeNumber information */

/* Field FailsafeFlightModeSwitchPosition information */



typedef struct __attribute__ ((__packed__)) {
    float Throttle;
    float Roll;
    float Pitch;
    float Yaw;
    float Collective;
    float Accessory0;
    float Accessory1;
    float Accessory2;
    float Accessory3;
}  ManualControlSettingsFailsafeChannelData ;
typedef struct __attribute__ ((__packed__)) {
    float array[9];
}  ManualControlSettingsFailsafeChannelDataArray ;
#define ManualControlSettingsFailsafeChannelToArray( var ) UAVObjectFieldToArray( ManualControlSettingsFailsafeChannelData, var )

typedef struct __attribute__ ((__packed__)) {
    int16_t Throttle;
    int16_t Roll;
    int16_t Pitch;
    int16_t Yaw;
    int16_t FlightMode;
    int16_t Collective;
    int16_t Accessory0;
    int16_t Accessory1;
    int16_t Accessory2;
    int16_t Accessory3;
    int16_t Rssi;
}  ManualControlSettingsChannelMinData ;
typedef struct __attribute__ ((__packed__)) {
    int16_t array[11];
}  ManualControlSettingsChannelMinDataArray ;
#define ManualControlSettingsChannelMinToArray( var ) UAVObjectFieldToArray( ManualControlSettingsChannelMinData, var )

typedef struct __attribute__ ((__packed__)) {
    int16_t Throttle;
    int16_t Roll;
    int16_t Pitch;
    int16_t Yaw;
    int16_t FlightMode;
    int16_t Collective;
    int16_t Accessory0;
    int16_t Accessory1;
    int16_t Accessory2;
    int16_t Accessory3;
    int16_t Rssi;
}  ManualControlSettingsChannelNeutralData ;
typedef struct __attribute__ ((__packed__)) {
    int16_t array[11];
}  ManualControlSettingsChannelNeutralDataArray ;
#define ManualControlSettingsChannelNeutralToArray( var ) UAVObjectFieldToArray( ManualControlSettingsChannelNeutralData, var )

typedef struct __attribute__ ((__packed__)) {
    int16_t Throttle;
    int16_t Roll;
    int16_t Pitch;
    int16_t Yaw;
    int16_t FlightMode;
    int16_t Collective;
    int16_t Accessory0;
    int16_t Accessory1;
    int16_t Accessory2;
    int16_t Accessory3;
    int16_t Rssi;
}  ManualControlSettingsChannelMaxData ;
typedef struct __attribute__ ((__packed__)) {
    int16_t array[11];
}  ManualControlSettingsChannelMaxDataArray ;
#define ManualControlSettingsChannelMaxToArray( var ) UAVObjectFieldToArray( ManualControlSettingsChannelMaxData, var )

typedef struct __attribute__ ((__packed__)) {
    uint16_t Roll;
    uint16_t Pitch;
    uint16_t Yaw;
    uint16_t Collective;
    uint16_t Accessory0;
    uint16_t Accessory1;
    uint16_t Accessory2;
    uint16_t Accessory3;
    uint16_t Rssi;
}  ManualControlSettingsResponseTimeData ;
typedef struct __attribute__ ((__packed__)) {
    uint16_t array[9];
}  ManualControlSettingsResponseTimeDataArray ;
#define ManualControlSettingsResponseTimeToArray( var ) UAVObjectFieldToArray( ManualControlSettingsResponseTimeData, var )

typedef struct __attribute__ ((__packed__)) {
    ManualControlSettingsChannelGroupsOptions Throttle;
    ManualControlSettingsChannelGroupsOptions Roll;
    ManualControlSettingsChannelGroupsOptions Pitch;
    ManualControlSettingsChannelGroupsOptions Yaw;
    ManualControlSettingsChannelGroupsOptions FlightMode;
    ManualControlSettingsChannelGroupsOptions Collective;
    ManualControlSettingsChannelGroupsOptions Accessory0;
    ManualControlSettingsChannelGroupsOptions Accessory1;
    ManualControlSettingsChannelGroupsOptions Accessory2;
    ManualControlSettingsChannelGroupsOptions Accessory3;
    ManualControlSettingsChannelGroupsOptions Rssi;
}  ManualControlSettingsChannelGroupsData ;
typedef struct __attribute__ ((__packed__)) {
    ManualControlSettingsChannelGroupsOptions array[11];
}  ManualControlSettingsChannelGroupsDataArray ;
#define ManualControlSettingsChannelGroupsToArray( var ) UAVObjectFieldToArray( ManualControlSettingsChannelGroupsData, var )

typedef struct __attribute__ ((__packed__)) {
    uint8_t Throttle;
    uint8_t Roll;
    uint8_t Pitch;
    uint8_t Yaw;
    uint8_t FlightMode;
    uint8_t Collective;
    uint8_t Accessory0;
    uint8_t Accessory1;
    uint8_t Accessory2;
    uint8_t Accessory3;
    uint8_t Rssi;
}  ManualControlSettingsChannelNumberData ;
typedef struct __attribute__ ((__packed__)) {
    uint8_t array[11];
}  ManualControlSettingsChannelNumberDataArray ;
#define ManualControlSettingsChannelNumberToArray( var ) UAVObjectFieldToArray( ManualControlSettingsChannelNumberData, var )


/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    ManualControlSettingsFailsafeChannelData FailsafeChannel;
    ManualControlSettingsChannelMinData ChannelMin;
    ManualControlSettingsChannelNeutralData ChannelNeutral;
    ManualControlSettingsChannelMaxData ChannelMax;
    ManualControlSettingsResponseTimeData ResponseTime;
    ManualControlSettingsChannelGroupsData ChannelGroups;
    ManualControlSettingsChannelNumberData ChannelNumber;
    uint8_t Deadband;
    uint8_t DeadbandAssistedControl;
    uint8_t FlightModeNumber;
    int8_t FailsafeFlightModeSwitchPosition;

} __attribute__((packed)) ManualControlSettingsDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef ManualControlSettingsDataPacked __attribute__((aligned(4))) ManualControlSettingsData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    ManualControlSettingsDataPacked data;
    byte arr[MANUALCONTROLSETTINGS_NUMBYTES];
 } ManualControlSettingsDataUnion;

#endif // MANUALCONTROLSETTINGS_H

/**
 * @}
 * @}
 */

