/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup AccelSensor AccelSensor
 * @brief Calibrated sensor data from 3 axis accelerometer in m/s².
 *
 * Autogenerated files and functions for AccelSensor Object
 *
 * @{
 *
 * @file       accelsensor.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the AccelSensor object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: accelsensor.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef ACCELSENSOR_H
#define ACCELSENSOR_H
#include <stdbool.h>
/* Object constants */
#define ACCELSENSOR_OBJID 0x8B7BBFB6
#define ACCELSENSOR_ISSINGLEINST 1
#define ACCELSENSOR_ISSETTINGS 0
#define ACCELSENSOR_ISPRIORITY 0
#define ACCELSENSOR_NUMBYTES sizeof(AccelSensorData)

/* Field x information */

/* Field y information */

/* Field z information */

/* Field temperature information */




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float x;
    float y;
    float z;
    float temperature;

} __attribute__((packed)) AccelSensorDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef AccelSensorDataPacked __attribute__((aligned(4))) AccelSensorData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    AccelSensorDataPacked data;
    byte arr[ACCELSENSOR_NUMBYTES];
 } AccelSensorDataUnion;

#endif // ACCELSENSOR_H

/**
 * @}
 * @}
 */
