/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup AttitudeState AttitudeState
 * @brief The updated Attitude estimation from @ref StateEstimationModule.
 *
 * Autogenerated files and functions for AttitudeState Object
 *
 * @{
 *
 * @file       attitudestate.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the AttitudeState object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: attitudestate.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef ATTITUDESTATE_H
#define ATTITUDESTATE_H
#include <stdbool.h>
/* Object constants */
#define ATTITUDESTATE_OBJID 0x7421C7BA
#define ATTITUDESTATE_ISSINGLEINST 1
#define ATTITUDESTATE_ISSETTINGS 0
#define ATTITUDESTATE_ISPRIORITY 0
#define ATTITUDESTATE_NUMBYTES sizeof(AttitudeStateData)

/* Field q1 information */

/* Field q2 information */

/* Field q3 information */

/* Field q4 information */

/* Field Roll information */

/* Field Pitch information */

/* Field Yaw information */

/* Field NavYaw information */




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float q1;
    float q2;
    float q3;
    float q4;
    float Roll;
    float Pitch;
    float Yaw;
    float NavYaw;

} __attribute__((packed)) AttitudeStateDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef AttitudeStateDataPacked __attribute__((aligned(4))) AttitudeStateData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    AttitudeStateDataPacked data;
    byte arr[ATTITUDESTATE_NUMBYTES];
 } AttitudeStateDataUnion;

#endif // ATTITUDESTATE_H

/**
 * @}
 * @}
 */
