/**
 ******************************************************************************
 * @addtogroup UAVObjects LibrePilot UAVObjects
 * @{
 * @addtogroup MagSensor MagSensor
 * @brief Calibrated sensor data from 3 axis magnetometer in MilliGauss.
 *
 * Autogenerated files and functions for MagSensor Object
 *
 * @{
 *
 * @file       magsensor.h
 *
 * @author     The LibrePilot Project, https://www.librepilot.org, (C) 2017.
 *             The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010-2013.
 *
 * @brief      Arduino Header of the MagSensor object. This file has been
 *             automatically generated by the UAVObjectGenerator.
 *
 * @note       Object definition file: magsensor.xml.
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef MAGSENSOR_H
#define MAGSENSOR_H
#include <stdbool.h>
/* Object constants */
#define MAGSENSOR_OBJID 0x70DAD456
#define MAGSENSOR_ISSINGLEINST 1
#define MAGSENSOR_ISSETTINGS 0
#define MAGSENSOR_ISPRIORITY 0
#define MAGSENSOR_NUMBYTES sizeof(MagSensorData)

/* Field x information */

/* Field y information */

/* Field z information */

/* Field temperature information */




/*
 * Packed Object data (unaligned).
 * Should only be used where 4 byte alignment can be guaranteed
 * (eg a single instance on the heap)
 */
typedef struct {
    float x;
    float y;
    float z;
    float temperature;

} __attribute__((packed)) MagSensorDataPacked;

/*
 * Packed Object data.
 * Alignment is forced to 4 bytes
 */
typedef MagSensorDataPacked __attribute__((aligned(4))) MagSensorData;

/*
 * Union to apply the data array to and to use as structured object data
 */
union {
    MagSensorDataPacked data;
    byte arr[MAGSENSOR_NUMBYTES];
 } MagSensorDataUnion;

#endif // MAGSENSOR_H

/**
 * @}
 * @}
 */
